### ISSUE TITLE
While running FLLM_schema-flan-t5.py this error pops up.

### ISSUE THREAD

**Issue by akash1003** [agiresearch/Formal-LLM#4]
ValueError: Asking to pad but the tokenizer does not have a padding token. Please select a token to use as `pad_token` `(tokenizer.pad_token = tokenizer.eos_token e.g.)` or add a new pad token via `tokenizer.add_special_tokens({'pad_token': '[PAD]'})`.

Tried adding 
if tokenizer.pad_token is None:     
              tokenizer.add_special_tokens({'pad_token': '[PAD]'})  
and 
tokenizer.pad_token = tokenizer.eos_token
 still doesn't seem to work

**Comment by lzl65825** [comment]
Hello,

I appreciate your interest in our project.

May I know which "tokenizer" you are referring to? Is it Flan-T5's tokenizer? If so, the tokenizer only encodes/decodes one text/tensor each time, so it will not apply padding.

**Comment by akash1003** [comment]
i debugged the problem is in the text generation tokeniser

**Comment by lzl65825** [comment]
Thank you for finding it. You can remove the padding since the code processes the text one by one and does not need to pad.
Change     Formal-LLM/src/combine_model_seq.py line 516 to
```
            inputs = self.text_generation_tokenizer(s, return_tensors="pt", truncation=True, max_length=512).to(device)
```
Let me know if the error still exists.
