### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered (Assertion `srcIndex < srcSelectDimSize` failed.)

### ISSUE THREAD

**Issue by akash1003** [agiresearch/Formal-LLM#5]
![Screenshot from 2024-04-09 12-05-07](https://github.com/agiresearch/Formal-LLM/assets/31279817/2157467f-47fd-41cb-8049-73aeb9043d17)

![Screenshot from 2024-04-09 12-03-03](https://github.com/agiresearch/Formal-LLM/assets/31279817/c5f363ec-2c90-4763-bdf5-d7ae6240a9f0)

When running this command (python open_source/FLLM_schema-flan-t5.py --log_name ./0.txt --cache_dir ./ --ckp_dir ./) as mentioned in the github repository, facing the above error. Could you please help me understand what is the problem,as I am using the exact codebase and dataset as given in the repo? I read on the pytorch discussion form it could be due to some out of bounds index somewhere.(https://discuss.pytorch.org/t/solved-assertion-srcindex-srcselectdimsize-failed-on-gpu-for-torch-cat/1804)

**Comment by lzl65825** [comment]
The error may come from the text generation tool (*self.text_generator* in FormalLLM/src/combine_model_seq.py). Have you removed all codes related to *self.text_generator_tokenizer*?
